
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AttendanceSession } from '../types';

/**
 * Generates and downloads a professional attendance report PDF.
 * Uses the explicit autoTable(doc, options) pattern which is more reliable in ESM environments.
 */
export const generateAttendancePDF = (session: AttendanceSession) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(30, 41, 59); // slate-800
  doc.text('Attendance Report', pageWidth / 2, 20, { align: 'center' });

  // Details Section
  doc.setFontSize(12);
  doc.setTextColor(71, 85, 105); // slate-600
  doc.text(`Class/Year: ${session.year}`, 20, 35);
  doc.text(`Subject/Lecture: ${session.lecture}`, 20, 42);
  doc.text(`Date: ${session.date}`, 140, 35);
  doc.text(`Time: ${session.time}`, 140, 42);

  const presentCount = session.presentRolls.size;
  const absentCount = session.totalStudents - presentCount;
  const attendancePercentage = ((presentCount / session.totalStudents) * 100).toFixed(1);

  // Statistics Header
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text('Summary', 20, 55);
  
  // Generate Table using the functional approach
  autoTable(doc, {
    startY: 60,
    head: [['Total Students', 'Present', 'Absent', 'Percentage']],
    body: [[session.totalStudents, presentCount, absentCount, `${attendancePercentage}%`]],
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229] }, // indigo-600
  });

  // Roll Number Lists
  const presentList = Array.from(session.presentRolls).sort((a, b) => a - b).join(', ');
  const absentList = Array.from({ length: session.totalStudents }, (_, i) => i + 1)
    .filter(roll => !session.presentRolls.has(roll))
    .sort((a, b) => a - b)
    .join(', ');

  // Get the Y position after the table
  const finalY = (doc as any).lastAutoTable.finalY || 80;
  const currentY = finalY + 15;

  doc.setFontSize(14);
  doc.text('Present Roll Numbers', 20, currentY);
  doc.setFontSize(10);
  const presentSplitText = doc.splitTextToSize(presentList || 'None', pageWidth - 40);
  doc.text(presentSplitText, 20, currentY + 7);

  const absentY = currentY + 15 + (presentSplitText.length * 5);
  doc.setFontSize(14);
  doc.text('Absent Roll Numbers', 20, absentY);
  doc.setFontSize(10);
  const absentSplitText = doc.splitTextToSize(absentList || 'None', pageWidth - 40);
  doc.text(absentSplitText, 20, absentY + 7);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(`Generated by SmartAttend | Coded by Rohsik | ${new Date().toLocaleString()}`, pageWidth / 2, footerY, { align: 'center' });

  // Save the PDF
  const safeYear = session.year.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const safeDate = session.date.replace(/\//g, '-');
  const filename = `Attendance_${safeYear}_${safeDate}.pdf`;
  doc.save(filename);
};
